[package]
name = "term-snake"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ['derive', 'help', 'usage', 'error-context'] }
clap_complete = "4.5.1"
crossterm = "0.27.0"
eyre = "0.6.12"
ndarray = "0.15.6"
rand = "0.8.5"
thiserror = "1.0.57"
